//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikProjeMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ELEKTRIKPROJEHAREKET
    {
        public int PROJEID1 { get; set; }
        public string PROJEAD1 { get; set; }
        public Nullable<int> MEVKI1 { get; set; }
        public Nullable<int> ADA1 { get; set; }
        public Nullable<int> PARSEL1 { get; set; }
        public Nullable<int> ELEKTRIKPROJENUSHA1 { get; set; }
        public string ELEKTRIKPROJEDURUM1 { get; set; }
        public string ELEKTRIKPROJEONYTAR1 { get; set; }
        public Nullable<int> TELEKOMPROJENUSHA1 { get; set; }
        public string TELEKOMPROJEDURUM1 { get; set; }
        public string TELEKOMPROJEONYTAR1 { get; set; }
        public string KONTROLFORMU1 { get; set; }
        public string TEDASDOSYASI1 { get; set; }
        public string ELEKTRIKCIAD1 { get; set; }
        public string ILETISIM1 { get; set; }
        public string ACIKLAMALAR1 { get; set; }
        public string FLAG1 { get; set; }
        public string ACIKLAMALAR21 { get; set; }
        public string ACIKLAMALAR31 { get; set; }
        public Nullable<int> SIRA1 { get; set; }
        public Nullable<int> PROJEIL1 { get; set; }
        public string TIKKONTROL1 { get; set; }
    }
}
